networks:
  - address: 10.0.0.0
    wildcard_bits: 0.0.0.255
    area: 0
  - address: 9.0.0.0
    wildcard_bits: 0.0.0.255
    area: 0
  - address: 7.0.0.0
    wildcard_bits: 0.0.0.255
    area: 0
l3_interfaces_config:
  - name: Ethernet0/1
    address: 10.0.0.1/24
  - name: Ethernet0/2
    address: 9.0.0.1/24
  - name: Ethernet0/3
    address: 7.0.0.1/24