networks:
  - address: 192.168.1.40
    wildcard_bits: 0.0.0.3
    area: 0
  - address: 192.168.1.44
    wildcard_bits: 0.0.0.3
    area: 0
  - address: 192.168.1.48
    wildcard_bits: 0.0.0.3
    area: 0
l3_interfaces_config:
  - name: Ethernet0/1
    address: 192.168.1.41/30
  - name: Ethernet0/2
    address: 192.168.1.45/30
  - name: Ethernet0/3
    address: 192.168.1.49/30