networks:
  - address: 11.0.0.0
    wildcard_bits: 0.0.0.255
    area: 1
  - address: 9.0.0.0
    wildcard_bits: 0.0.0.255
    area: 0
  - address: 8.0.0.0
    wildcard_bits: 0.0.0.255
    area: 2
l3_interfaces_config:
  - name: Ethernet0/1
    address: 11.0.0.1/24
  - name: Ethernet0/2
    address: 9.0.0.2/24
  - name: Ethernet0/3
    address: 8.0.0.1/24