networks:
  - address: 192.168.1.52
    wildcard_bits: 0.0.0.3
    area: 1
  - address: 192.168.1.44
    wildcard_bits: 0.0.0.3
    area: 0
  - address: 192.168.1.56
    wildcard_bits: 0.0.0.3
    area: 2
l3_interfaces_config:
  - name: Ethernet0/1
    address: 192.168.1.53/30
  - name: Ethernet0/2
    address: 192.168.1.46/30
  - name: Ethernet0/3
    address: 192.168.1.57/30