networks:
  - address: 192.168.1.40
    wildcard_bits: 0.0.0.3
    area: 0
  - address: 192.168.1.8
    wildcard_bits: 0.0.0.7
    area: 0
l3_interfaces_config:
  - name: Ethernet0/1
    address: 192.168.1.42/30
  - name: Ethernet0/2
    address: 192.168.1.9/29
dhcp:
  pool: R15
  network: 192.168.1.7
  default_router: 192.168.1.8