networks:
  - address: 192.168.1.64
    wildcard_bits: 0.0.0.3
    area: 1
  - address: 192.168.1.24
    wildcard_bits: 0.0.0.7
    area: 1
l3_interfaces_config:
  - name: Ethernet0/1
    address: 192.168.1.66/30
  - name: Ethernet0/2
    address: 192.168.1.25/29
dhcp:
  pool: R17
  network: 192.168.1.24
  default_router: 192.168.1.25