networks:
  - address: 192.168.1.48
    wildcard_bits: 0.0.0.3
    area: 0
  - address: 192.168.1.0
    wildcard_bits: 0.0.0.7
    area: 0
l3_interfaces_config:
  - name: Ethernet0/1
    address: 192.168.1.50/30
  - name: Ethernet0/2
    address: 192.168.1.1/29
dhcp:
  pool: R4
  network: 192.168.1.0
  default_router: 192.168.1.1