networks:
  - address: 192.168.1.60
    wildcard_bits: 0.0.0.3
    area: 2
  - address: 192.168.1.32
    wildcard_bits: 0.0.0.7
    area: 2
l3_interfaces_config:
  - name: Ethernet0/1
    address: 192.168.1.62/30
  - name: Ethernet0/2
    address: 192.168.1.33/29
dhcp:
  pool: R8
  network: 192.168.1.32
  default_router: 192.168.1.33